# Generated by Django 6.0.4 on 2026-05-17 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0005_protocolexecution_current_step_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolexecution',
            name='client_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='UUID do cliente para idempotência'),
        ),
        migrations.AddConstraint(
            model_name='protocolexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('physician', 'client_uuid'), name='unique_protocol_execution_client_uuid_per_physician'),
        ),
    ]
